// swift-tools-version:5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

// Set it to true to use local binary (for development)
let useLocalBinary = true

// URL and checksum of prebuilt rust Core
let binaryUrl = "https://github.com/tesseract-one/Tesseract.swift/releases/download/0.5.2/Tesseract-Core.bin.zip"
let binaryChecksum = "6c3e43be4bc464bad0054873aed3c18bea8336f1e02028445b8dc04b3c9a192a"

// Package description
let package = Package(
    name: "Tesseract",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "TesseractClient",
            targets: ["TesseractClient"]),
        .library(
            name: "TesseractService",
            targets: ["TesseractService"]),
        .library(
            name: "TesseractShared",
            targets: ["TesseractShared"]),
        .library(
            name: "TesseractTransportsClient",
            targets: ["TesseractTransportsClient"]),
        .library(
            name: "TesseractTransportsService",
            targets: ["TesseractTransportsService"]),
        .library(
            name: "TesseractTransportsShared",
            targets: ["TesseractTransportsShared"]),
        .library(
            name: "TesseractUtils",
            targets: ["TesseractUtils"])
    ],
    dependencies: [],
    targets: [
        .target(
            name: "TesseractClient",
            dependencies: ["TesseractTransportsClient", "TesseractShared"]),
        .target(
            name: "TesseractService",
            dependencies: ["TesseractTransportsService", "TesseractShared"]),
        .target(
            name: "TesseractShared",
            dependencies: ["TesseractTransportsShared", "CTesseract"]),
        .target(
            name: "TesseractTransportsClient",
            dependencies: ["TesseractTransportsShared"]),
        .target(
            name: "TesseractTransportsService",
            dependencies: ["TesseractTransportsShared"]),
        .target(
            name: "TesseractTransportsShared",
            dependencies: ["TesseractUtils"]),
        .target(
            name: "TesseractUtils",
            dependencies: ["CTesseractShared"]),
        // Header only target. Headers generated by Rust/generate_headers.sh
        .target(name: "CTesseractShared", dependencies: []),
        // Binary target
        useLocalBinary
            ? .binaryTarget(name: "CTesseract", path: "CTesseract.xcframework")
            : .binaryTarget(name: "CTesseract", url: binaryUrl, checksum: binaryChecksum)
    ]
)
