#pragma once

/* Generated with cbindgen:0.24.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
@import CTesseractUtils;

typedef struct TransportProcessor {
  SyncPtr_Void _0;
} TransportProcessor;

typedef CAnyDropPtr BoundTransport;

typedef struct Transport {
  CAnyDropPtr ptr;
  BoundTransport (*bind)(struct Transport transport, struct TransportProcessor processor);
} Transport;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

CFuture_CData transport_processor_process(struct TransportProcessor processor,
                                          const uint8_t *data,
                                          uintptr_t len);

void transport_processor_free(struct TransportProcessor *processor);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
