#pragma once

/* Generated with cbindgen:0.24.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

enum CErrorCodes
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  CErrorCodes_EmptyRequest = 0,
  CErrorCodes_EmptyResponse,
  CErrorCodes_UnsupportedDataType,
  CErrorCodes_RequestExpired,
  CErrorCodes_WrongProtocolId,
  CErrorCodes_WrongInternalState,
};
#ifndef __cplusplus
typedef uint32_t CErrorCodes;
#endif // __cplusplus
