#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "tesseract-swift-utils.h"
#include "tesseract-swift-transports.h"

typedef enum LogLevel {
  LogLevel_Off,
  LogLevel_Error,
  LogLevel_Warn,
  LogLevel_Info,
  LogLevel_Debug,
  LogLevel_Trace,
} LogLevel;

typedef enum SubstrateAccountType {
  SubstrateAccountType_Ed25519,
  SubstrateAccountType_Sr25519,
  SubstrateAccountType_Ecdsa,
} SubstrateAccountType;

typedef struct ServiceTesseract {
  SyncPtr_Void _0;
} ServiceTesseract;

typedef struct TestService {
  CAnyDropPtr ptr;
  CFutureString (*sign_transaction)(const struct TestService *this, CStringRef req);
} TestService;

typedef struct SubstrateGetAccountResponse {
  CData public_key;
  CString path;
} SubstrateGetAccountResponse;

typedef void (*CFutureOnCompleteCallback_SubstrateGetAccountResponse)(SyncPtr_Void context,
                                                                      struct SubstrateGetAccountResponse *value,
                                                                      CError *error);

typedef struct CFuture_SubstrateGetAccountResponse {
  CAnyDropPtr ptr;
  COptionResponseResult (*set_on_complete)(const struct CFuture_SubstrateGetAccountResponse *future,
                                           SyncPtr_Void context,
                                           struct SubstrateGetAccountResponse *value,
                                           CError *error,
                                           CFutureOnCompleteCallback_SubstrateGetAccountResponse cb);
} CFuture_SubstrateGetAccountResponse;

typedef struct SubstrateService {
  CAnyDropPtr ptr;
  struct CFuture_SubstrateGetAccountResponse (*get_account)(const struct SubstrateService *this,
                                                            enum SubstrateAccountType account_type);
  CFutureData (*sign_transaction)(const struct SubstrateService *this,
                                  enum SubstrateAccountType account_type,
                                  CStringRef account_path,
                                  CDataRef extrinsic_data,
                                  CDataRef extrinsic_metadata,
                                  CDataRef extrinsic_types);
} SubstrateService;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct ServiceTesseract tesseract_service_new(void);

struct ServiceTesseract tesseract_service_add_transport(struct ServiceTesseract *tesseract,
                                                        ServiceTransport transport);

void tesseract_service_free(struct ServiceTesseract *tesseract);

struct ServiceTesseract tesseract_service_add_test_service(struct ServiceTesseract *tesseract,
                                                           struct TestService service);

void tesseract_substrate_get_account_response_free(struct SubstrateGetAccountResponse *res);

struct ServiceTesseract tesseract_service_add_substrate_service(struct ServiceTesseract *tesseract,
                                                                struct SubstrateService service);

bool tesseract_sdk_init(enum LogLevel log, CError *error);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
