#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "tesseract-swift-utils.h"

enum CTesseractErrorCode
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  CTesseractErrorCode_Cancelled = CErrorCode_Sentinel,
  CTesseractErrorCode_Serialization,
  CTesseractErrorCode_Weird,
  /**
   * Must be last for serialization purposes
   */
  CTesseractErrorCode_Sentinel,
};
#ifndef __cplusplus
typedef uint32_t CTesseractErrorCode;
#endif // __cplusplus

typedef enum CTesseractError_Tag {
  CTesseractError_Null,
  CTesseractError_Panic,
  CTesseractError_Logger,
  CTesseractError_Utf8,
  CTesseractError_Cast,
  CTesseractError_Swift,
  CTesseractError_Cancelled,
  CTesseractError_Serialization,
  CTesseractError_Weird,
  CTesseractError_Custom,
} CTesseractError_Tag;

typedef struct CTesseractError_Custom_Body {
  uint32_t _0;
  CString _1;
} CTesseractError_Custom_Body;

typedef struct CTesseractError {
  CTesseractError_Tag tag;
  union {
    struct {
      CString null;
    };
    struct {
      CString panic;
    };
    struct {
      CString logger;
    };
    struct {
      CString utf8;
    };
    struct {
      CString cast;
    };
    struct {
      SwiftError swift;
    };
    struct {
      CString serialization;
    };
    struct {
      CString weird;
    };
    CTesseractError_Custom_Body custom;
  };
} CTesseractError;

typedef struct ServiceTransportProcessor {
  SyncPtr_Void _0;
} ServiceTransportProcessor;

typedef enum ClientStatus_Tag {
  ClientStatus_Ready,
  ClientStatus_Unavailable,
  ClientStatus_Error,
} ClientStatus_Tag;

typedef struct ClientStatus {
  ClientStatus_Tag tag;
  union {
    struct {
      CString unavailable;
    };
    struct {
      CError error;
    };
  };
} ClientStatus;

typedef void (*CFutureOnCompleteCallback_ClientStatus)(SyncPtr_Void context,
                                                       struct ClientStatus *value,
                                                       CError *error);

typedef struct CFuture_ClientStatus {
  CAnyDropPtr ptr;
  COptionResponseResult (*set_on_complete)(const struct CFuture_ClientStatus *future,
                                           SyncPtr_Void context,
                                           struct ClientStatus *value,
                                           CError *error,
                                           CFutureOnCompleteCallback_ClientStatus cb);
} CFuture_ClientStatus;

typedef struct ClientConnection {
  CAnyDropPtr ptr;
  CFuture_Nothing (*send)(const struct ClientConnection *connection,
                          const uint8_t *data,
                          uintptr_t len);
  CFuture_CData (*receive)(const struct ClientConnection *connection);
} ClientConnection;

typedef struct ClientTransport {
  CAnyDropPtr ptr;
  CString (*id)(const struct ClientTransport *transport);
  struct CFuture_ClientStatus (*status)(const struct ClientTransport *transport, CStringRef protocol);
  struct ClientConnection (*connect)(const struct ClientTransport *transport, CStringRef protocol);
} ClientTransport;

typedef struct CFuture_ClientStatus CFutureClientStatus;

typedef CAnyDropPtr ServiceBoundTransport;

typedef struct ServiceTransport {
  CAnyDropPtr ptr;
  ServiceBoundTransport (*bind)(struct ServiceTransport transport,
                                struct ServiceTransportProcessor processor);
} ServiceTransport;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct CTesseractError tesseract_error_from_cerror(CError *cerr);

CError tesseract_error_to_cerror(struct CTesseractError *core);

CString tesseract_error_get_description(const struct CTesseractError *err);

void tesseract_error_free(struct CTesseractError *core);

CFuture_CData tesseract_service_transport_processor_process(struct ServiceTransportProcessor processor,
                                                            const uint8_t *data,
                                                            uintptr_t len);

void tesseract_service_transport_processor_free(struct ServiceTransportProcessor *processor);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
