#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "tesseract-swift-utils.h"
#include "tesseract-swift-shared.h"

typedef enum ClientStatus_Tag {
  ClientStatus_Ready,
  ClientStatus_Unavailable,
  ClientStatus_Error,
} ClientStatus_Tag;

typedef struct ClientStatus {
  ClientStatus_Tag tag;
  union {
    struct {
      CString unavailable;
    };
    struct {
      CError error;
    };
  };
} ClientStatus;

typedef enum CFutureValue_ClientStatus_Tag {
  CFutureValue_ClientStatus_None_ClientStatus,
  CFutureValue_ClientStatus_Value_ClientStatus,
  CFutureValue_ClientStatus_Error_ClientStatus,
} CFutureValue_ClientStatus_Tag;

typedef struct CFutureValue_ClientStatus {
  CFutureValue_ClientStatus_Tag tag;
  union {
    struct {
      struct ClientStatus value;
    };
    struct {
      CError error;
    };
  };
} CFutureValue_ClientStatus;

typedef void (*CFutureOnCompleteCallback_ClientStatus)(SyncPtr_Void context,
                                                       struct ClientStatus *value,
                                                       CError *error);

typedef struct CFuture_ClientStatus {
  CAnyDropPtr ptr;
  struct CFutureValue_ClientStatus (*set_on_complete)(const struct CFuture_ClientStatus *future,
                                                      SyncPtr_Void context,
                                                      CFutureOnCompleteCallback_ClientStatus cb);
} CFuture_ClientStatus;

typedef struct ClientConnection {
  CAnyDropPtr ptr;
  CFuture_Nothing (*send)(const struct ClientConnection *connection,
                          const uint8_t *data,
                          uintptr_t len);
  CFuture_CData (*receive)(const struct ClientConnection *connection);
} ClientConnection;

typedef struct ClientTransport {
  CAnyDropPtr ptr;
  CString (*id)(const struct ClientTransport *transport);
  struct CFuture_ClientStatus (*status)(const struct ClientTransport *transport, CStringRef protocol);
  struct ClientConnection (*connect)(const struct ClientTransport *transport, CStringRef protocol);
} ClientTransport;

typedef struct CFuture_ClientStatus CFutureClientStatus;
