#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "tesseract-swift-utils.h"

enum CTesseractErrorCode
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  CTesseractErrorCode_Logger = CErrorCode_Sentinel,
  CTesseractErrorCode_Cancelled,
  CTesseractErrorCode_Serialization,
  CTesseractErrorCode_Weird,
  /**
   * Must be last for serialization purposes
   */
  CTesseractErrorCode_Sentinel,
};
#ifndef __cplusplus
typedef uint32_t CTesseractErrorCode;
#endif // __cplusplus

typedef struct ServiceTransportProcessor {
  SyncPtr_Void _0;
} ServiceTransportProcessor;

typedef enum ClientStatus_Tag {
  ClientStatus_Ready,
  ClientStatus_Unavailable,
  ClientStatus_Error,
} ClientStatus_Tag;

typedef struct ClientStatus {
  ClientStatus_Tag tag;
  union {
    struct {
      CString unavailable;
    };
    struct {
      CError error;
    };
  };
} ClientStatus;

typedef void (*CFutureOnCompleteCallback_ClientStatus)(SyncPtr_Void context,
                                                       struct ClientStatus *value,
                                                       CError *error);

typedef struct CFuture_ClientStatus {
  CAnyDropPtr ptr;
  COptionResponseResult (*set_on_complete)(const struct CFuture_ClientStatus *future,
                                           SyncPtr_Void context,
                                           struct ClientStatus *value,
                                           CError *error,
                                           CFutureOnCompleteCallback_ClientStatus cb);
} CFuture_ClientStatus;

typedef struct ClientConnection {
  CAnyDropPtr ptr;
  CFuture_Nothing (*send)(const struct ClientConnection *connection,
                          const uint8_t *data,
                          uintptr_t len);
  CFuture_CData (*receive)(const struct ClientConnection *connection);
} ClientConnection;

typedef struct ClientTransport {
  CAnyDropPtr ptr;
  CString (*id)(const struct ClientTransport *transport);
  struct CFuture_ClientStatus (*status)(const struct ClientTransport *transport, CStringRef protocol);
  struct ClientConnection (*connect)(const struct ClientTransport *transport, CStringRef protocol);
} ClientTransport;

typedef struct CFuture_ClientStatus CFutureClientStatus;

typedef CAnyDropPtr ServiceBoundTransport;

typedef struct ServiceTransport {
  CAnyDropPtr ptr;
  ServiceBoundTransport (*bind)(struct ServiceTransport transport,
                                struct ServiceTransportProcessor processor);
} ServiceTransport;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

CString tesseract_error_get_description(const CError *err);

CFuture_CData tesseract_service_transport_processor_process(struct ServiceTransportProcessor processor,
                                                            const uint8_t *data,
                                                            uintptr_t len);

void tesseract_service_transport_processor_free(struct ServiceTransportProcessor *processor);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
