#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "tesseract-swift-utils.h"

enum CErrorCodes
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  CErrorCodes_EmptyRequest = 0,
  CErrorCodes_EmptyResponse,
  CErrorCodes_UnsupportedDataType,
  CErrorCodes_RequestExpired,
  CErrorCodes_WrongProtocolId,
  CErrorCodes_WrongInternalState,
  CErrorCodes_Serialization,
  CErrorCodes_Nested,
};
#ifndef __cplusplus
typedef uint32_t CErrorCodes;
#endif // __cplusplus

typedef struct ServiceTransportProcessor {
  SyncPtr_Void _0;
} ServiceTransportProcessor;

typedef enum ClientStatus_Tag {
  ClientStatus_Ready,
  ClientStatus_Unavailable,
  ClientStatus_Error,
} ClientStatus_Tag;

typedef struct ClientStatus {
  ClientStatus_Tag tag;
  union {
    struct {
      CString unavailable;
    };
    struct {
      CError error;
    };
  };
} ClientStatus;

typedef enum CFutureValue_ClientStatus_Tag {
  CFutureValue_ClientStatus_None_ClientStatus,
  CFutureValue_ClientStatus_Value_ClientStatus,
  CFutureValue_ClientStatus_Error_ClientStatus,
} CFutureValue_ClientStatus_Tag;

typedef struct CFutureValue_ClientStatus {
  CFutureValue_ClientStatus_Tag tag;
  union {
    struct {
      struct ClientStatus value;
    };
    struct {
      CError error;
    };
  };
} CFutureValue_ClientStatus;

typedef void (*CFutureOnCompleteCallback_ClientStatus)(SyncPtr_Void context,
                                                       struct ClientStatus *value,
                                                       CError *error);

typedef struct CFuture_ClientStatus {
  CAnyDropPtr ptr;
  struct CFutureValue_ClientStatus (*set_on_complete)(const struct CFuture_ClientStatus *future,
                                                      SyncPtr_Void context,
                                                      CFutureOnCompleteCallback_ClientStatus cb);
} CFuture_ClientStatus;

typedef struct ClientConnection {
  CAnyDropPtr ptr;
  CFuture_Nothing (*send)(const struct ClientConnection *connection,
                          const uint8_t *data,
                          uintptr_t len);
  CFuture_CData (*receive)(const struct ClientConnection *connection);
} ClientConnection;

typedef struct ClientTransport {
  CAnyDropPtr ptr;
  CString (*id)(const struct ClientTransport *transport);
  struct CFuture_ClientStatus (*status)(const struct ClientTransport *transport, CStringRef protocol);
  struct ClientConnection (*connect)(const struct ClientTransport *transport, CStringRef protocol);
} ClientTransport;

typedef struct CFuture_ClientStatus CFutureClientStatus;

typedef CAnyDropPtr ServiceBoundTransport;

typedef struct ServiceTransport {
  CAnyDropPtr ptr;
  ServiceBoundTransport (*bind)(struct ServiceTransport transport,
                                struct ServiceTransportProcessor processor);
} ServiceTransport;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

CFuture_CData tesseract_service_transport_processor_process(struct ServiceTransportProcessor processor,
                                                            const uint8_t *data,
                                                            uintptr_t len);

void tesseract_service_transport_processor_free(struct ServiceTransportProcessor *processor);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
