name: Publish CocoaPods package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
      - name: Set release version
        run: sed -i '' "s|[[:blank:]]*s\.version[[:blank:]].*|s.version = '${VERSION}'|g" *.podspec
        env: 
          VERSION: ${{ github.event.release.tag_name }}
      - name: Set Core binary URL
        run:
          FILE_URL=$(sed -n 's|let[[:blank:]]*binaryUrl[[:blank:]]*=[[:blank:]]*"\(.*\)"|\1|p' Package.swift)
          SHA=$(sed -n 's|let[[:blank:]]*binaryChecksum[[:blank:]]*=[[:blank:]]*"\(.*\)"|\1|p' Package.swift)
          POD_SOURCE="s.source = { :http => '${FILE_URL}', :sha256 => '${SHA}' }"
          sed -i '' "s|[[:blank:]]*s\.source[[:blank:]].*|${POD_SOURCE}|g" Tesseract-Core.podspec
      - name: Update CocoaPods repo
        run: pod repo update
      - name: Publish Core Pod
        run: pod trunk push --allow-warnings --synchronous Tesseract-Core.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Publish Shared Pod
        run: pod trunk push --allow-warnings --synchronous Tesseract-Shared.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Publish Client Pod
        run: pod trunk push --allow-warnings --synchronous Tesseract-Client.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Publish Service Pod
        run: pod trunk push --allow-warnings --synchronous Tesseract-Service.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}